server:
    servlet: 
        context-path: /dev

spring: 
    thymeleaf:
        cache: false
        
hikari:
    master:
        jdbc-url: jdbc:mysql://localhost:3306/my-project?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
        username: root
        password: 1qaz8ik,
        maximum-pool-size: 20
        pool-name: master
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000
    slave:
        jdbc-url: jdbc:mysql://localhost:3306/my-project-read?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
        username: root
        password: 1qaz8ik,
        maximum-pool-size: 80
        pool-name: slave
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000
        read-only: true