server:
    port: 8090

spring: 
    profiles: 
        active: dev
        
logging:
    config: classpath:logback-spring.xml
    
mybatis: 
    type-aliases-package: com.ysertine.*.entity
    mapper-locations: classpath:/mybatis/*/*.xml
    configuration: 
        map-underscore-to-camel-case: true